# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 09:51
from __future__ import unicode_literals

from django.db import migrations


def forward(apps, schema_editor):
    if schema_editor.connection.vendor.startswith('postgres'):
        schema_editor.execute("""
            CREATE OR REPLACE VIEW meetings_meetingnextrepetition AS
            SELECT DISTINCT ON (meetings_meetingrepetition.meeting_id) meetings_meetingrepetition.id,
                meetings_meetingrepetition.date,
                meetings_meetingrepetition.meeting_id,
                meetings_meetingrepetition.id AS repetition_id
            FROM meetings_meetingrepetition
            WHERE meetings_meetingrepetition.date >= now()
            ORDER BY meetings_meetingrepetition.meeting_id, meetings_meetingrepetition.date
            """)
    else:
        # Basically SQLLite version for testing. Canonical SQL version for the problem, without distict on available.
        schema_editor.execute("""
            CREATE VIEW if NOT EXISTS meetings_meetingnextrepetition AS
            SELECT 
                r1.id,
                r1.date,
                r1.meeting_id,
                r1.id AS repetition_id
            FROM meetings_meetingrepetition r1
            WHERE 
                r1.date >= date('now')
                AND NOT exists (SELECT 1 FROM meetings_meetingrepetition r2 WHERE r2.meeting_id = r1.meeting_id AND r2.date > r1.date AND r2.date > r1.date)
            ORDER BY r1.meeting_id, r1.date
            """)


def backward(apps, schema_editor):
    schema_editor.execute('DROP VIEW meetings_meetingnextrepetition')


class Migration(migrations.Migration):
    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forward, backward)
    ]
